[java]
extensions = ["java"]

[java-properties]
extensions = ["properties"]

[kotlin]
extensions = ["kt", "kts"]

[python]
extensions = ["py"]

[lua]
extensions = ["lua", "eel"]

[shellscript]
extensions = ["sh"]

[xml]
extensions = ["xml", "xsd", "svg"]

[json]
extensions = ["json", "jsonc"]

[jsonl]
extensions = ["jsonl", "ndjson" ]

[html]
extensions = ["html", "htm"]

[toml]
extensions = ["toml"]

[javascript]
extensions = ["js", "jsx", "mjs", "cjs"]

[typescript]
extensions = ["ts", "tsx"]

[markdown]
extensions = ["md", "markdown", "mkdown", "mkd", "mdown"]
